### ISSUE TITLE
turbopy 2021 -> NFE 2022

### ISSUE THREAD

**Issue by padamson** [NRL-Plasma-Physics-Division/nfe-2022-turbopy#1]
#### Description
Update descriptions, etc, to reference NFE 2022.

#### Files
Probably just the README, but should review all of the files.

#### Tasks

- [x] Update description in README to reference origin of curriculum and how it will be used in NFE 2022 (see comment below)
- [x] Fix links in README to point to public version of repo
- [x] Remove reference to Syntek orientation

**Comment by padamson** [comment]
Add the following info to README:

@padamson will host office hours and seminars on MS Teams. Some other researchers at NRL will also participate and possibly help lead these sessions. They will be recorded and distributed for anyone who can’t attend a specific day/time.
 
Please let @padamson know your github.com username so he can add you to the NFE 2022 team on the site.
 
A lot of the interaction and learning will be via this git repo for the boot camp at https://github.com/NRL-Plasma-Physics-Division/nfe-2022-turbopy. Please go ahead and fork it (if you know what that is…if not, don’t worry, we’ll learn about that!). If you are really comfortable with git and github, you can start interacting right away through issues and pull requests.
 
@padamson will be sending out a short survey to gauge everyone’s background/proficiency with Python, git, and various software engineering concepts so that we can tailor the boot camp for the group (or perhaps individually if there is a range of experience).
 
@padamson will be sending out Doodle polls to find out preferences for seminars and office hours. But don’t worry if they don’t land on a day/time that is convenient…they will be recorded and distributed. Also, everything is pretty well documented in this repo, so most of the curriculum can be done completely async and self-paced, if that is preferred.
 
If you have any questions at all, please contact @padamson.

**Comment by padamson** [comment]
Done with 0e2889cb
